### ISSUE TITLE
Could I use you code with modification in my disseration?

### ISSUE THREAD

**Issue by BlueNewew** [timkittel/alpha-shapes#2]
Hello developer,

I am a master student and my dissertation topic is about 3D point cloud reconstruction. Could your code apply on three-dimensional conditions? and could I use it with modifications for reconstruct my data? If okay, I will cite you in my code as well as my paper and appreciate you in my acknowledgment.

Neil

**Comment by timziebart** [comment]
The code is for 3-dimensional point clouds. I am not sure about your questions, as you didn't actually state what you want to do exactly. But you are free to use the code when following the license and I would be happy if you would cite https://arxiv.org/abs/1706.04542 .
