### ISSUE TITLE
Edges to polygon

### ISSUE THREAD

**Issue by swarmt** [timkittel/alpha-shapes#3]
This is great!

Could you suggest a method to get the outer vertices in clockwise order to create a polygon?

**Comment by timziebart** [comment]
Hi,

can you elaborate what you mean? If I understand correctly, you are working with 2d alpha shapes? The current code here is just written for 3d. You could adjust the code for 2d (a PR would be welcome). Afterwards, I think you can start at one edge, find the matching next one, and iterate that until you are done. Is that what you imagined?

Cheers,
Tim

**Comment by swarmt** [comment]
Sorry Tim that was a bit vague.

I found exactly what I am looking for in here.
https://pysal.readthedocs.io/en/latest/_modules/pysal/lib/cg/alpha_shapes.html#alpha_shape
